# Generated by Django 4.1.2 on 2022-11-08 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_spam_contacts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spam_contacts',
            options={'verbose_name': 'Спам для контакта', 'verbose_name_plural': ''},
        ),
    ]
