# Generated by Django 4.1.2 on 2022-11-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AlterField(
            model_name='service',
            name='experience',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='hour_from',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='hour_to',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
