# Generated by Django 4.1.2 on 2022-11-07 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_favorite_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
